### ISSUE TITLE
无法设置透明度

### ISSUE THREAD

**Issue by bestsort** [Airsaid/InspireWritingPlugin#1]
您好:
非常感谢您制作了此款插件. 我已经使用此插件接近半个月了，体验一级棒！

但是有件事很困扰我: 

每当插件更换新壁纸的时候，总是会将透明度重置为 15% 而不是我自己设置的 20%. 这就使得我的壁纸不大看得出来(都是暗色调),但是每次手动调整又太麻烦. 

不知道能不能改为每次更换新壁纸后维持透明度不变

**Comment by Airsaid** [comment]
您好，非常感谢使用和反馈！

最新的 V1.0.3 版本中已经增加了对不透明度的支持。

首先需要通过 IDEA 自带的 ”Set Background Image“ 修改一次背景，然后 “Inspire Writing“ 就会延用其中的不透明度等参数。

需要注意的是，图片的名称当中不能包含 , 符号，因为 “Set Background Image“ 是以该符号来作为参数之间的分割的。如果图片中包含了该符号，“Set Background Image“ 自身就会无法识别出该图片。
